#!/bin/bash
#
# script to Export Drupal Settings using Drush 9
# and delete unneeded settings (Ignore) as in CMI Tools
#
# script to backup the Drupal Database and Essential Settings
# to a dated folder inside Backups Folder
#
dateStamp=`eval date +%Y-%m-%d_%H-%M-%S`
DIRECTORY=~/Backups/SITEFOLDER/$dateStamp
if [[ -d "${DIRECTORY}" && ! -L "${DIRECTORY}" ]] ; then
    echo "Saving Database and Settings to $DIRECTORY"
else
    echo "Saving Database and Settings to $DIRECTORY"
    mkdir -p "${DIRECTORY}"
fi
drush sql-dump --gzip --result-file "${DIRECTORY}/database.sql"
cp web/sites/default/se* "${DIRECTORY}"
echo "Finished"
ls -lh "${DIRECTORY}"
echo "Exporting the Settings to config/sync"
echo
drush cex sync -y
echo
echo "Finished - Ready to git commit -am ..... and push"
echo
echo "This script and the importConfigSync assume you have already"
echo "installed the drupal/config_ignore module and added 'system.site'"
echo "to the ignore list"
