#!/bin/bash
#
# script to Import Drupal Settings using Drush 9
# and delete unneeded settings (Ignore) as in CMI Tools
#
dateStamp=`eval date +%Y-%m-%d_%H-%M-%S`
cd web
DIRECTORY=~/Backups/SITEFOLDER/$dateStamp
if [[ -d "${DIRECTORY}" && ! -L "${DIRECTORY}" ]] ; then
    echo "Saving Database and Settings to $DIRECTORY"
else
    echo "Saving Database and Settings to $DIRECTORY"
    mkdir -p "${DIRECTORY}"
fi
drush sql-dump --gzip --result-file "${DIRECTORY}/database.sql"
cp sites/default/se* "${DIRECTORY}"
echo "Finished"
ls -lh "${DIRECTORY}"

cd web
echo "Importing the Settings from config/sync"
echo
echo "Removing Unnecessary Settings"
echo
cp -v ../config/active/system.site.yml ../config/sync/
cp -v ../config/active/contact*.yml ../config/sync/
cp -v ../config/active/shortcut.set.default.yml ../config/sync/
cp -v ../config/active/field.field.contact_message.*.yml ../config/sync/
cp -v ../config/active/field.storage.contact_message.*.yml ../config/sync/
cp -v ../config/active/core.entity_form_display.contact_message*.yml ../config/sync/
cp -v ../config/active/core.entity_form_display.contact_form*.yml ../config/sync/
cp -v ../config/active/core.entity_view_display.contact_message*.yml ../config/sync/
cp -v ../config/active/core.entity_view_display.contact_form*.yml ../config/sync/
cp -v ../config/active/workbench_email.workbench_email_template.*.yml ../config/sync/
echo
drush cim sync
echo
drush updb
drush cr
echo "Finished - Ready to test the updates"
echo

