#!/bin/bash
#
# script to Export Drupal Settings using Drush 9
# and delete unneeded settings (Ignore) as in CMI Tools
#
cd web
echo "Exporting the Settings to config/sync"
echo
drush cex sync -y
echo
echo "Removing Unnecessary Settings"
echo
rm -v ../config/sync/system.site.yml
rm -v ../config/sync/contact*.yml
rm -v ../config/sync/shortcut.set.default.yml
rm -v ../config/sync/field.field.contact_message.*.yml
rm -v ../config/sync/field.storage.contact_message.*.yml
rm -v ../config/sync/core.entity_form_display.contact_message*.yml
rm -v ../config/sync/core.entity_form_display.contact_form*.yml
rm -v ../config/sync/core.entity_view_display.contact_message*.yml
rm -v ../config/sync/core.entity_view_display.contact_form*.yml
rm -v ../config/sync/workbench_email.workbench_email_template.*.yml
echo
echo "Finished - Ready to git commit -am ..... and push"
echo

